# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawFhir2OmopClient, RawFhir2OmopClient
from .types.create_omop_response import CreateOmopResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class Fhir2OmopClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFhir2OmopClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFhir2OmopClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFhir2OmopClient
        """
        return self._raw_client

    def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateOmopResponse:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
        (person, visit_occurrence, condition_occurrence, drug_exposure,
        procedure_occurrence, measurement, observation).

        Resource support is intentionally limited to the OMOP tables returned by
        this endpoint:
        - `Patient` -> `person`
        - `Encounter` -> `visit_occurrence`
        - `Condition` -> `condition_occurrence`
        - `Procedure` -> `procedure_occurrence`
        - `MedicationRequest`, `MedicationStatement`, and
          `MedicationAdministration` -> `drug_exposure`
        - `Immunization` -> `drug_exposure`
        - `Observation` with a numeric `valueQuantity`, `valueInteger`, or
          numeric-looking `valueString` (for example `"<2"`) -> `measurement`
        - non-numeric `Observation` -> `observation`
        - `AllergyIntolerance` -> `observation`

        `Medication` is supported only as reference data for medication
        resources; it is not emitted as its own row because OMOP CDM has no
        Medication table. Other reference/admin resources such as `Practitioner`,
        `Organization`, `Location`, `Coverage`, and `Claim`, and clinical
        workflow/document resources such as `DiagnosticReport`, `ServiceRequest`,
        `CarePlan`, `DocumentReference`, `Composition`, `Specimen`, and
        `DeviceUseStatement`, are currently accepted in a Bundle but are not
        shaped into OMOP rows. Unsupported resource types are ignored rather than
        listed under `dropped`; `dropped` is reserved for supported resource types
        that were missing the subject/patient, code, or medication reference data
        needed to produce a valid row.

        Each resource's primary clinical coding is resolved to a standard OMOP
        `concept_id`. Alongside the OMOP rows grouped by table (`tables`), the
        response carries `mappings` (how each source coding resolved, linked back
        to the row it produced), `dropped` (resources that could not be shaped
        into a row), `vocab_version` (the OMOP vocabulary release codes were
        resolved against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Only the primary clinical coding is resolved, so
        `gender`/`race`/`ethnicity`/`visit`/`value`/`unit` `concept_id`s are
        always `0`; the one populated non-resolved concept is measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than the resolver. Each `*_source_value` carries the verbatim FHIR
        coding (`system#code`), and `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The
        bundle must contain at least one Patient resource.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Supported row-producing resources are Patient,
            Encounter, Condition, Procedure, MedicationRequest,
            MedicationStatement, MedicationAdministration, Immunization,
            Observation, and AllergyIntolerance. Standalone Medication resources
            are consumed by medication references rather than mapped to their own
            table. Other resource types are accepted but ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOmopResponse
            FHIR resources mapped to OMOP CDM v5.4

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.fhir2omop.create(
            fhir_resources={
                "resourceType": "Bundle",
                "type": "collection",
                "entry": [
                    {
                        "resource": {
                            "resourceType": "Patient",
                            "id": "patient-1",
                            "gender": "female",
                            "birthDate": "1985-07-22",
                        }
                    },
                    {
                        "resource": {
                            "resourceType": "Condition",
                            "id": "condition-1",
                            "subject": {"reference": "Patient/patient-1"},
                            "code": {
                                "coding": [
                                    {
                                        "system": "http://snomed.info/sct",
                                        "code": "44054006",
                                        "display": "Type 2 diabetes mellitus",
                                    }
                                ]
                            },
                            "onsetDateTime": "2024-01-15",
                        }
                    },
                    {
                        "resource": {
                            "resourceType": "MedicationRequest",
                            "id": "medreq-1",
                            "status": "active",
                            "subject": {"reference": "Patient/patient-1"},
                            "medicationReference": {"reference": "#med0"},
                            "authoredOn": "2024-01-16",
                            "contained": [
                                {
                                    "resourceType": "Medication",
                                    "id": "med0",
                                    "code": {
                                        "coding": [
                                            {
                                                "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                                                "code": "860975",
                                                "display": "metformin hydrochloride 500 MG",
                                            }
                                        ]
                                    },
                                }
                            ],
                        }
                    },
                ],
            },
        )
        """
        _response = self._raw_client.create(fhir_resources=fhir_resources, request_options=request_options)
        return _response.data


class AsyncFhir2OmopClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFhir2OmopClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFhir2OmopClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFhir2OmopClient
        """
        return self._raw_client

    async def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> CreateOmopResponse:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
        (person, visit_occurrence, condition_occurrence, drug_exposure,
        procedure_occurrence, measurement, observation).

        Resource support is intentionally limited to the OMOP tables returned by
        this endpoint:
        - `Patient` -> `person`
        - `Encounter` -> `visit_occurrence`
        - `Condition` -> `condition_occurrence`
        - `Procedure` -> `procedure_occurrence`
        - `MedicationRequest`, `MedicationStatement`, and
          `MedicationAdministration` -> `drug_exposure`
        - `Immunization` -> `drug_exposure`
        - `Observation` with a numeric `valueQuantity`, `valueInteger`, or
          numeric-looking `valueString` (for example `"<2"`) -> `measurement`
        - non-numeric `Observation` -> `observation`
        - `AllergyIntolerance` -> `observation`

        `Medication` is supported only as reference data for medication
        resources; it is not emitted as its own row because OMOP CDM has no
        Medication table. Other reference/admin resources such as `Practitioner`,
        `Organization`, `Location`, `Coverage`, and `Claim`, and clinical
        workflow/document resources such as `DiagnosticReport`, `ServiceRequest`,
        `CarePlan`, `DocumentReference`, `Composition`, `Specimen`, and
        `DeviceUseStatement`, are currently accepted in a Bundle but are not
        shaped into OMOP rows. Unsupported resource types are ignored rather than
        listed under `dropped`; `dropped` is reserved for supported resource types
        that were missing the subject/patient, code, or medication reference data
        needed to produce a valid row.

        Each resource's primary clinical coding is resolved to a standard OMOP
        `concept_id`. Alongside the OMOP rows grouped by table (`tables`), the
        response carries `mappings` (how each source coding resolved, linked back
        to the row it produced), `dropped` (resources that could not be shaped
        into a row), `vocab_version` (the OMOP vocabulary release codes were
        resolved against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Only the primary clinical coding is resolved, so
        `gender`/`race`/`ethnicity`/`visit`/`value`/`unit` `concept_id`s are
        always `0`; the one populated non-resolved concept is measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than the resolver. Each `*_source_value` carries the verbatim FHIR
        coding (`system#code`), and `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The
        bundle must contain at least one Patient resource.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Supported row-producing resources are Patient,
            Encounter, Condition, Procedure, MedicationRequest,
            MedicationStatement, MedicationAdministration, Immunization,
            Observation, and AllergyIntolerance. Standalone Medication resources
            are consumed by medication references rather than mapped to their own
            table. Other resource types are accepted but ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateOmopResponse
            FHIR resources mapped to OMOP CDM v5.4

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.fhir2omop.create(
                fhir_resources={
                    "resourceType": "Bundle",
                    "type": "collection",
                    "entry": [
                        {
                            "resource": {
                                "resourceType": "Patient",
                                "id": "patient-1",
                                "gender": "female",
                                "birthDate": "1985-07-22",
                            }
                        },
                        {
                            "resource": {
                                "resourceType": "Condition",
                                "id": "condition-1",
                                "subject": {"reference": "Patient/patient-1"},
                                "code": {
                                    "coding": [
                                        {
                                            "system": "http://snomed.info/sct",
                                            "code": "44054006",
                                            "display": "Type 2 diabetes mellitus",
                                        }
                                    ]
                                },
                                "onsetDateTime": "2024-01-15",
                            }
                        },
                        {
                            "resource": {
                                "resourceType": "MedicationRequest",
                                "id": "medreq-1",
                                "status": "active",
                                "subject": {"reference": "Patient/patient-1"},
                                "medicationReference": {"reference": "#med0"},
                                "authoredOn": "2024-01-16",
                                "contained": [
                                    {
                                        "resourceType": "Medication",
                                        "id": "med0",
                                        "code": {
                                            "coding": [
                                                {
                                                    "system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                                                    "code": "860975",
                                                    "display": "metformin hydrochloride 500 MG",
                                                }
                                            ]
                                        },
                                    }
                                ],
                            }
                        },
                    ],
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(fhir_resources=fhir_resources, request_options=request_options)
        return _response.data
