# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .errors.bad_request_error import BadRequestError
from .errors.internal_server_error import InternalServerError
from .errors.service_unavailable_error import ServiceUnavailableError
from .errors.unauthorized_error import UnauthorizedError
from .types.create_omop_response import CreateOmopResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFhir2OmopClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreateOmopResponse]:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
        (person, visit_occurrence, condition_occurrence, drug_exposure,
        procedure_occurrence, measurement, observation).

        Each resource's primary clinical coding is resolved to a standard OMOP
        `concept_id`. Alongside the OMOP rows grouped by table (`tables`), the
        response carries `mappings` (how each source coding resolved, linked back
        to the row it produced), `dropped` (resources that could not be shaped
        into a row), `vocab_version` (the OMOP vocabulary release codes were
        resolved against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Only the primary clinical coding is resolved, so
        `gender`/`race`/`ethnicity`/`visit`/`value`/`unit` `concept_id`s are
        always `0`; the one populated non-resolved concept is measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than the resolver. Each `*_source_value` carries the verbatim FHIR
        coding (`system#code`), and `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The
        bundle must contain at least one Patient resource.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Resources are mapped to OMOP rows; standalone
            Medication resources are consumed by medication references rather than
            mapped to their own table.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateOmopResponse]
            FHIR resources mapped to OMOP CDM v5.4
        """
        _response = self._client_wrapper.httpx_client.request(
            "fhir2omop/create",
            method="POST",
            json={
                "fhir_resources": fhir_resources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateOmopResponse,
                    parse_obj_as(
                        type_=CreateOmopResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFhir2OmopClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreateOmopResponse]:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows
        (person, visit_occurrence, condition_occurrence, drug_exposure,
        procedure_occurrence, measurement, observation).

        Each resource's primary clinical coding is resolved to a standard OMOP
        `concept_id`. Alongside the OMOP rows grouped by table (`tables`), the
        response carries `mappings` (how each source coding resolved, linked back
        to the row it produced), `dropped` (resources that could not be shaped
        into a row), `vocab_version` (the OMOP vocabulary release codes were
        resolved against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Only the primary clinical coding is resolved, so
        `gender`/`race`/`ethnicity`/`visit`/`value`/`unit` `concept_id`s are
        always `0`; the one populated non-resolved concept is measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than the resolver. Each `*_source_value` carries the verbatim FHIR
        coding (`system#code`), and `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The
        bundle must contain at least one Patient resource.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Resources are mapped to OMOP rows; standalone
            Medication resources are consumed by medication references rather than
            mapped to their own table.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateOmopResponse]
            FHIR resources mapped to OMOP CDM v5.4
        """
        _response = await self._client_wrapper.httpx_client.request(
            "fhir2omop/create",
            method="POST",
            json={
                "fhir_resources": fhir_resources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateOmopResponse,
                    parse_obj_as(
                        type_=CreateOmopResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
