# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from .errors.bad_request_error import BadRequestError
from .errors.internal_server_error import InternalServerError
from .errors.service_unavailable_error import ServiceUnavailableError
from .errors.unauthorized_error import UnauthorizedError
from .types.create_omop_response import CreateOmopResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFhir2OmopClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[CreateOmopResponse]:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows,
        grouped by destination table in `tables`.

        Current resource coverage:
        - `Patient` -> `person`; `deceased[x]` can also produce `death`, and the
          first address can produce `location`
        - `observation_period` -> one derived row per person with dated visit,
          clinical, or death rows, spanning those dates
        - `Location` -> `location` and `care_site`
        - `Organization` -> `care_site`; its first address can produce `location`
        - `HealthcareService` -> `care_site`
        - `Practitioner` and `PractitionerRole` -> `provider`
        - `Encounter` -> `visit_occurrence`
        - `Condition` -> `condition_occurrence`
        - `Procedure` -> `procedure_occurrence`
        - `MedicationRequest`, `MedicationStatement`, and
          `MedicationAdministration` -> `drug_exposure`
        - `Immunization` -> `drug_exposure`
        - `Observation` -> `measurement` or `observation`. For coded
          Observations, the resolved OMOP concept domain selects the table; value
          form only breaks ties. For text-only Observations, numeric values route
          to `measurement` and nonnumeric values to `observation`.
        - `AllergyIntolerance` -> `observation`

        `Medication` is reference data for medication resources; it does not
        create its own row because OMOP CDM has no Medication table. Administrative
        linkages (provider, care site, and location) are best-effort and limited to
        references supplied in the request. Their supporting concepts, including
        provider specialty, country, and place of service, are not mapped.

        `DiagnosticReport`, `ServiceRequest`, `CarePlan`, `DocumentReference`,
        `Composition`, `Specimen`, `DeviceUseStatement`, `Coverage`, `Claim`, and
        other unsupported resource types are accepted in a Bundle but ignored: they
        create no row and no `dropped` entry. `dropped` is reserved for supported
        row-producing resources that could not be shaped because the subject/patient,
        clinical code/text, or medication data was not usable. A single-Patient
        Bundle can attribute a supported clinical resource with a missing or
        unresolvable subject to that sole person; in a multi-Patient Bundle, that
        resource is dropped instead.

        Coded Observation routing is selected from the resolved OMOP concept
        domain. Numeric and nonnumeric `value[x]` forms establish the preferred
        target only when the code is valid for both tables. A text-only
        Observation has no resolver target, so numeric values route to
        `measurement` and nonnumeric values to `observation`. Numeric values
        populate `value_as_number` in the selected row; nonnumeric values
        populate `value_as_string` for an `observation` or `value_source_value`
        for a `measurement`. `valueCodeableConcept` remains source text and does
        not populate `value_as_concept_id`; other unsupported `value[x]` forms
        and Observation components do not populate separate converted values. A
        numeric comparator (`<`, `<=`, `>`, `>=`) is represented only by a
        measurement's `operator_concept_id`; units remain source text and have
        `unit_concept_id` of `0`.

        A single standard OMOP `concept_id` is selected for each clinical row
        after considering all of the resource's supplied codings. Alongside the
        OMOP rows grouped by table (`tables`), the response carries `mappings`
        (an entry for every source coding, linked back to the row it produced),
        `dropped` (resources that could not be shaped into a row),
        `vocab_version` (the OMOP vocabulary release codes were resolved
        against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Demographic, visit, categorical-value, and unit concept
        fields currently remain `0`; the one populated non-resolved concept is
        measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than terminology resolution. Clinical `*_source_value` fields
        preserve the selected FHIR coding (`system#code`, or `code` when no
        system is supplied), falling back to source text for text-only resources.
        Other `*_source_value` fields preserve row-specific raw source values,
        such as resource identifiers, names, units, or status codes, and
        `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The Bundle must contain at
        least one Patient resource.

        All row IDs start at `1` for each request and are not stable or global.
        For clinical conversion rows whose resource supplies an `id`, `mappings`
        associates each row with that source FHIR resource ID. A `person` row
        retains the Patient ID or its first identifier value in
        `person_source_value`, when present; other reference and derived rows do
        not uniformly carry a FHIR resource ID. Input resources without those
        source identifiers cannot be correlated across responses from the
        returned rows alone. Consumers combining responses need to establish
        their own stable keys and remap every primary and foreign key together.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Supported row-producing resources are Patient,
            Location, Organization, HealthcareService, Practitioner,
            PractitionerRole, Encounter, Condition, Procedure, MedicationRequest,
            MedicationStatement, MedicationAdministration, Immunization,
            Observation, and AllergyIntolerance. Standalone Medication resources
            are consumed by medication references rather than mapped to their own
            table. Unsupported resource types are accepted in a Bundle but ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateOmopResponse]
            FHIR resources mapped to OMOP CDM v5.4
        """
        _response = self._client_wrapper.httpx_client.request(
            "fhir2omop/create",
            method="POST",
            json={
                "fhir_resources": fhir_resources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateOmopResponse,
                    parse_obj_as(
                        type_=CreateOmopResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFhir2OmopClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self, *, fhir_resources: typing.Dict[str, typing.Any], request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[CreateOmopResponse]:
        """
        Maps a FHIR R4 resource or Bundle into OMOP Common Data Model v5.4 rows,
        grouped by destination table in `tables`.

        Current resource coverage:
        - `Patient` -> `person`; `deceased[x]` can also produce `death`, and the
          first address can produce `location`
        - `observation_period` -> one derived row per person with dated visit,
          clinical, or death rows, spanning those dates
        - `Location` -> `location` and `care_site`
        - `Organization` -> `care_site`; its first address can produce `location`
        - `HealthcareService` -> `care_site`
        - `Practitioner` and `PractitionerRole` -> `provider`
        - `Encounter` -> `visit_occurrence`
        - `Condition` -> `condition_occurrence`
        - `Procedure` -> `procedure_occurrence`
        - `MedicationRequest`, `MedicationStatement`, and
          `MedicationAdministration` -> `drug_exposure`
        - `Immunization` -> `drug_exposure`
        - `Observation` -> `measurement` or `observation`. For coded
          Observations, the resolved OMOP concept domain selects the table; value
          form only breaks ties. For text-only Observations, numeric values route
          to `measurement` and nonnumeric values to `observation`.
        - `AllergyIntolerance` -> `observation`

        `Medication` is reference data for medication resources; it does not
        create its own row because OMOP CDM has no Medication table. Administrative
        linkages (provider, care site, and location) are best-effort and limited to
        references supplied in the request. Their supporting concepts, including
        provider specialty, country, and place of service, are not mapped.

        `DiagnosticReport`, `ServiceRequest`, `CarePlan`, `DocumentReference`,
        `Composition`, `Specimen`, `DeviceUseStatement`, `Coverage`, `Claim`, and
        other unsupported resource types are accepted in a Bundle but ignored: they
        create no row and no `dropped` entry. `dropped` is reserved for supported
        row-producing resources that could not be shaped because the subject/patient,
        clinical code/text, or medication data was not usable. A single-Patient
        Bundle can attribute a supported clinical resource with a missing or
        unresolvable subject to that sole person; in a multi-Patient Bundle, that
        resource is dropped instead.

        Coded Observation routing is selected from the resolved OMOP concept
        domain. Numeric and nonnumeric `value[x]` forms establish the preferred
        target only when the code is valid for both tables. A text-only
        Observation has no resolver target, so numeric values route to
        `measurement` and nonnumeric values to `observation`. Numeric values
        populate `value_as_number` in the selected row; nonnumeric values
        populate `value_as_string` for an `observation` or `value_source_value`
        for a `measurement`. `valueCodeableConcept` remains source text and does
        not populate `value_as_concept_id`; other unsupported `value[x]` forms
        and Observation components do not populate separate converted values. A
        numeric comparator (`<`, `<=`, `>`, `>=`) is represented only by a
        measurement's `operator_concept_id`; units remain source text and have
        `unit_concept_id` of `0`.

        A single standard OMOP `concept_id` is selected for each clinical row
        after considering all of the resource's supplied codings. Alongside the
        OMOP rows grouped by table (`tables`), the response carries `mappings`
        (an entry for every source coding, linked back to the row it produced),
        `dropped` (resources that could not be shaped into a row),
        `vocab_version` (the OMOP vocabulary release codes were resolved
        against), and a small `summary` of the resolution outcomes.

        A `concept_id` of `0` is reported, not omitted (OMOP "no matching
        concept" semantics): it covers both a coding with no standard match
        (`UNMAPPED`) and an unverified suggestion for a text-only resource
        (`UNCHECKED`). Demographic, visit, categorical-value, and unit concept
        fields currently remain `0`; the one populated non-resolved concept is
        measurement
        `operator_concept_id`, set from a value comparator (`<`, `<=`, `>`, `>=`)
        rather than terminology resolution. Clinical `*_source_value` fields
        preserve the selected FHIR coding (`system#code`, or `code` when no
        system is supplied), falling back to source text for text-only resources.
        Other `*_source_value` fields preserve row-specific raw source values,
        such as resource identifiers, names, units, or status codes, and
        `*_type_concept_id` is set to `32817` (EHR).

        Medication codes are resolved whether they appear inline
        (`medicationCodeableConcept`) or via a `medicationReference` to a contained,
        relative (`Type/id`), or bundle-entry (`urn:uuid`) `Medication` resource.
        Resources that cannot be shaped into a row — a medication with no usable
        code, resolvable reference, or display, or any clinical resource whose
        subject/patient reference cannot be tied to a person — are reported under
        `dropped` rather than emitted as blank rows. The Bundle must contain at
        least one Patient resource.

        All row IDs start at `1` for each request and are not stable or global.
        For clinical conversion rows whose resource supplies an `id`, `mappings`
        associates each row with that source FHIR resource ID. A `person` row
        retains the Patient ID or its first identifier value in
        `person_source_value`, when present; other reference and derived rows do
        not uniformly carry a FHIR resource ID. Input resources without those
        source identifiers cannot be correlated across responses from the
        returned rows alone. Consumers combining responses need to establish
        their own stable keys and remap every primary and foreign key together.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle). Must contain at least one
            Patient resource. Supported row-producing resources are Patient,
            Location, Organization, HealthcareService, Practitioner,
            PractitionerRole, Encounter, Condition, Procedure, MedicationRequest,
            MedicationStatement, MedicationAdministration, Immunization,
            Observation, and AllergyIntolerance. Standalone Medication resources
            are consumed by medication references rather than mapped to their own
            table. Unsupported resource types are accepted in a Bundle but ignored.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateOmopResponse]
            FHIR resources mapped to OMOP CDM v5.4
        """
        _response = await self._client_wrapper.httpx_client.request(
            "fhir2omop/create",
            method="POST",
            json={
                "fhir_resources": fhir_resources,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateOmopResponse,
                    parse_obj_as(
                        type_=CreateOmopResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
