# This file was auto-generated by Fern from our API Definition.

import typing

CernerRole = typing.Union[
    typing.Literal[
        "CernerSmartV1Admin",
        "CernerSmartV1Read",
        "CernerSmartV1Write",
        "CernerSmartV2Admin",
        "CernerSmartV2Read",
        "CernerSmartV2Write",
    ],
    typing.Any,
]
