# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .fhir_implementation_guide import FhirImplementationGuide


class ImplementationGuideVersionDetail(UniversalBaseModel):
    name: str
    url: str
    version: str
    profile_context: str
    profiles: typing.List[str]
    profile_refs: typing.List[str]
    implementation_guide: FhirImplementationGuide
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
