# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawAgentClient, RawAgentClient
from .types.agent_create_request_provider import AgentCreateRequestProvider
from .types.agent_delete_response import AgentDeleteResponse
from .types.agent_list_response import AgentListResponse
from .types.agent_response import AgentResponse
from .types.json_patch import JsonPatch

if typing.TYPE_CHECKING:
    from .chat.client import AsyncChatClient, ChatClient
    from .prompts.client import AsyncPromptsClient, PromptsClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._chat: typing.Optional[ChatClient] = None
        self._prompts: typing.Optional[PromptsClient] = None

    @property
    def with_raw_response(self) -> RawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentClient
        """
        return self._raw_client

    def create(
        self,
        *,
        name: str,
        prompts: typing.Sequence[str],
        provider: AgentCreateRequestProvider,
        description: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[str]] = OMIT,
        workflows: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Creates a new PhenoAgent with specified configuration

        Parameters
        ----------
        name : str
            Agent name

        prompts : typing.Sequence[str]
            Array of prompt IDs to use for this agent

        provider : AgentCreateRequestProvider
            FHIR provider ID(s) for this agent. Required.
            In shared/experiment environments, the default sandbox provider is used if a different provider is not explicitly specified.

        description : typing.Optional[str]
            Agent description

        tools : typing.Optional[typing.Sequence[str]]
            Array of MCP server tool IDs to use for this agent

        workflows : typing.Optional[typing.Sequence[str]]
            Array of workflow IDs to expose as tools for this agent

        tags : typing.Optional[typing.Sequence[str]]
            Tags for categorizing the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent created successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.create(
            name="Medical Assistant",
            description="An AI assistant for medical information processing",
            prompts=["prompt_123"],
            tags=["medical", "fhir"],
            provider="7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        )
        """
        _response = self._raw_client.create(
            name=name,
            prompts=prompts,
            provider=provider,
            description=description,
            tools=tools,
            workflows=workflows,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    def list(
        self, *, tags: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentListResponse:
        """
        Retrieves a list of PhenoAgents belonging to the authenticated user

        Parameters
        ----------
        tags : typing.Optional[str]
            Filter by tags

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentListResponse
            Agents retrieved successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.list(
            tags="tags",
        )
        """
        _response = self._raw_client.list(tags=tags, request_options=request_options)
        return _response.data

    def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AgentResponse:
        """
        Retrieves a specific agent by its ID

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent retrieved successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.get(
            id="id",
        )
        """
        _response = self._raw_client.get(id, request_options=request_options)
        return _response.data

    def update(
        self,
        id: str,
        *,
        name: str,
        prompts: typing.Sequence[str],
        provider: AgentCreateRequestProvider,
        description: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[str]] = OMIT,
        workflows: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Updates an existing agent's configuration

        Parameters
        ----------
        id : str
            Agent ID

        name : str
            Agent name

        prompts : typing.Sequence[str]
            Array of prompt IDs to use for this agent

        provider : AgentCreateRequestProvider
            FHIR provider ID(s) for this agent. Required.
            In shared/experiment environments, the default sandbox provider is used if a different provider is not explicitly specified.

        description : typing.Optional[str]
            Agent description

        tools : typing.Optional[typing.Sequence[str]]
            Array of MCP server tool IDs to use for this agent

        workflows : typing.Optional[typing.Sequence[str]]
            Array of workflow IDs to expose as tools for this agent

        tags : typing.Optional[typing.Sequence[str]]
            Tags for categorizing the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent updated successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.update(
            id="id",
            name="Medical Assistant",
            description="Updated description for the medical assistant",
            prompts=["prompt_123"],
            tags=["medical", "fhir", "updated"],
            provider="7002b0b4-8d09-445a-bf65-0fafdaf26c35",
        )
        """
        _response = self._raw_client.update(
            id,
            name=name,
            prompts=prompts,
            provider=provider,
            description=description,
            tools=tools,
            workflows=workflows,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AgentDeleteResponse:
        """
        Deletes an existing agent

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentDeleteResponse
            Agent deleted successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.delete(
            id="id",
        )
        """
        _response = self._raw_client.delete(id, request_options=request_options)
        return _response.data

    def patch(
        self, id: str, *, request: JsonPatch, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentResponse:
        """
        Patches an existing agent's configuration

        Parameters
        ----------
        id : str
            Agent ID

        request : JsonPatch

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent patched successfully

        Examples
        --------
        from phenoml import PhenomlClient
        from phenoml.agent import JsonPatchOperation

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.agent.patch(
            id="id",
            request=[
                JsonPatchOperation(
                    op="replace",
                    path="/description",
                    value="patched description",
                ),
                JsonPatchOperation(
                    op="add",
                    path="/tags/-",
                    value="updated",
                ),
            ],
        )
        """
        _response = self._raw_client.patch(id, request=request, request_options=request_options)
        return _response.data

    @property
    def chat(self):
        if self._chat is None:
            from .chat.client import ChatClient  # noqa: E402

            self._chat = ChatClient(client_wrapper=self._client_wrapper)
        return self._chat

    @property
    def prompts(self):
        if self._prompts is None:
            from .prompts.client import PromptsClient  # noqa: E402

            self._prompts = PromptsClient(client_wrapper=self._client_wrapper)
        return self._prompts


class AsyncAgentClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._chat: typing.Optional[AsyncChatClient] = None
        self._prompts: typing.Optional[AsyncPromptsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawAgentClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        name: str,
        prompts: typing.Sequence[str],
        provider: AgentCreateRequestProvider,
        description: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[str]] = OMIT,
        workflows: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Creates a new PhenoAgent with specified configuration

        Parameters
        ----------
        name : str
            Agent name

        prompts : typing.Sequence[str]
            Array of prompt IDs to use for this agent

        provider : AgentCreateRequestProvider
            FHIR provider ID(s) for this agent. Required.
            In shared/experiment environments, the default sandbox provider is used if a different provider is not explicitly specified.

        description : typing.Optional[str]
            Agent description

        tools : typing.Optional[typing.Sequence[str]]
            Array of MCP server tool IDs to use for this agent

        workflows : typing.Optional[typing.Sequence[str]]
            Array of workflow IDs to expose as tools for this agent

        tags : typing.Optional[typing.Sequence[str]]
            Tags for categorizing the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent created successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.create(
                name="Medical Assistant",
                description="An AI assistant for medical information processing",
                prompts=["prompt_123"],
                tags=["medical", "fhir"],
                provider="7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            name=name,
            prompts=prompts,
            provider=provider,
            description=description,
            tools=tools,
            workflows=workflows,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    async def list(
        self, *, tags: typing.Optional[str] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentListResponse:
        """
        Retrieves a list of PhenoAgents belonging to the authenticated user

        Parameters
        ----------
        tags : typing.Optional[str]
            Filter by tags

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentListResponse
            Agents retrieved successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.list(
                tags="tags",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(tags=tags, request_options=request_options)
        return _response.data

    async def get(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AgentResponse:
        """
        Retrieves a specific agent by its ID

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent retrieved successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.get(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, request_options=request_options)
        return _response.data

    async def update(
        self,
        id: str,
        *,
        name: str,
        prompts: typing.Sequence[str],
        provider: AgentCreateRequestProvider,
        description: typing.Optional[str] = OMIT,
        tools: typing.Optional[typing.Sequence[str]] = OMIT,
        workflows: typing.Optional[typing.Sequence[str]] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AgentResponse:
        """
        Updates an existing agent's configuration

        Parameters
        ----------
        id : str
            Agent ID

        name : str
            Agent name

        prompts : typing.Sequence[str]
            Array of prompt IDs to use for this agent

        provider : AgentCreateRequestProvider
            FHIR provider ID(s) for this agent. Required.
            In shared/experiment environments, the default sandbox provider is used if a different provider is not explicitly specified.

        description : typing.Optional[str]
            Agent description

        tools : typing.Optional[typing.Sequence[str]]
            Array of MCP server tool IDs to use for this agent

        workflows : typing.Optional[typing.Sequence[str]]
            Array of workflow IDs to expose as tools for this agent

        tags : typing.Optional[typing.Sequence[str]]
            Tags for categorizing the agent

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent updated successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.update(
                id="id",
                name="Medical Assistant",
                description="Updated description for the medical assistant",
                prompts=["prompt_123"],
                tags=["medical", "fhir", "updated"],
                provider="7002b0b4-8d09-445a-bf65-0fafdaf26c35",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update(
            id,
            name=name,
            prompts=prompts,
            provider=provider,
            description=description,
            tools=tools,
            workflows=workflows,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    async def delete(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> AgentDeleteResponse:
        """
        Deletes an existing agent

        Parameters
        ----------
        id : str
            Agent ID

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentDeleteResponse
            Agent deleted successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.delete(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, request_options=request_options)
        return _response.data

    async def patch(
        self, id: str, *, request: JsonPatch, request_options: typing.Optional[RequestOptions] = None
    ) -> AgentResponse:
        """
        Patches an existing agent's configuration

        Parameters
        ----------
        id : str
            Agent ID

        request : JsonPatch

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AgentResponse
            Agent patched successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient
        from phenoml.agent import JsonPatchOperation

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.agent.patch(
                id="id",
                request=[
                    JsonPatchOperation(
                        op="replace",
                        path="/description",
                        value="patched description",
                    ),
                    JsonPatchOperation(
                        op="add",
                        path="/tags/-",
                        value="updated",
                    ),
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.patch(id, request=request, request_options=request_options)
        return _response.data

    @property
    def chat(self):
        if self._chat is None:
            from .chat.client import AsyncChatClient  # noqa: E402

            self._chat = AsyncChatClient(client_wrapper=self._client_wrapper)
        return self._chat

    @property
    def prompts(self):
        if self._prompts is None:
            from .prompts.client import AsyncPromptsClient  # noqa: E402

            self._prompts = AsyncPromptsClient(client_wrapper=self._client_wrapper)
        return self._prompts
