# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2
from .fhir_resource import FhirResource
from .profile_summary import ProfileSummary


class ProfileGetResponse(ProfileSummary):
    """
    Metadata and full StructureDefinition JSON for either a custom profile's current StructureDefinition or one retained version.
    """

    structure_definition: FhirResource = pydantic.Field()
    """
    The full FHIR StructureDefinition JSON.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
