# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .profile_summary_source import ProfileSummarySource


class ProfileSummary(UniversalBaseModel):
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The lowercase StructureDefinition id, used as the profile's lookup key.
    """

    source: typing.Optional[ProfileSummarySource] = pydantic.Field(default=None)
    """
    The profile's origin. Listings currently return only custom (uploaded) profiles, so this is always "custom" today; built-in (US Core / R4 base) profiles would be surfaced via an opt-in parameter in a future release, not by changing the default behavior.
    """

    resource_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The FHIR resource type from the StructureDefinition.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The canonical URL from the StructureDefinition.
    """

    version: typing.Optional[str] = pydantic.Field(default=None)
    """
    The version from the StructureDefinition.version field.
    """

    fhir_version: typing.Optional[str] = pydantic.Field(default=None)
    """
    The base FHIR version the StructureDefinition targets.
    """

    implementation_guide: typing.Optional[str] = pydantic.Field(default=None)
    """
    The implementation guide the profile belongs to.
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
