# This file was auto-generated by Fern from our API Definition.

import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawLang2FhirBatchClient, RawLang2FhirBatchClient
from .types.batch_job import BatchJob
from .types.job_detail_response import JobDetailResponse
from .types.job_list_response import JobListResponse
from .types.results_page_response import ResultsPageResponse
from .types.upload_item_response import UploadItemResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class Lang2FhirBatchClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawLang2FhirBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawLang2FhirBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawLang2FhirBatchClient
        """
        return self._raw_client

    def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobListResponse:
        """
        Returns a page of the instance's batch jobs, newest first, without
        per-job counts. Jobs are shared across the instance's credentials, so
        this lists every batch job on the instance, not just the calling
        credential's.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobListResponse
            A page of batch jobs

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.list(
            cursor="cursor",
            limit=1,
        )
        """
        _response = self._raw_client.list(cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    def create(
        self, *, request_id: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchJob:
        """
        Opens an empty job; upload items, then finalize it to start processing.

        `request_id` makes creation idempotent: a retry returns the original
        job. A token is released when its job is canceled or fails before
        finalization; otherwise it continues to resolve to that job.

        Parameters
        ----------
        request_id : typing.Optional[str]
            Optional client idempotency token (at most 256 UTF-8 bytes). A
            retried create with the same token returns the original job instead
            of opening a second one.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            Batch job created (or an idempotent replay of an existing job)

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.create(
            request_id="submit-2025-09-02-batch-001",
        )
        """
        _response = self._raw_client.create(request_id=request_id, request_options=request_options)
        return _response.data

    def upload_item(
        self,
        job_id: str,
        *,
        document: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        create: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        file: typing.Optional[core.File] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadItemResponse:
        """
        Stores one multipart item. Set **either** `document` with a raw `file`,
        or JSON-only `create`.

        Set exactly one JSON object. `document` requires `file`; `create`
        forbids it. Violations return `400`.

        Upload validates only the envelope. Endpoint request validation happens
        during processing: decoding failures are `invalid_input`; other pipeline
        failures are `processing_failed`.

        Use `request_id` for every upload so retries replace the same item.
        `deduplicated` is true only for an unchanged payload; a changed payload
        overwrites the item and returns false.

        Uploads return `409` after finalization or at the item limit, and `413`
        when the item is too large.

        Parameters
        ----------
        job_id : str

        document : typing.Optional[typing.Dict[str, typing.Any]]
            The JSON body of `POST /lang2fhir/document/multi`, **without**
            its base64 `content` field — the uploaded `file` supplies the
            content. Accepts that endpoint's fields (`version`, `provider`,
            `primary_patient`, `patient_reference` (deprecated), `implementation_guide`, `detection_effort`,
            `validation_method`, `config`). This is the **multi**-resource
            body: it has no single-`resource` field, and the item's result
            is a `DocumentMultiResponse` (a Bundle of resources). Mutually
            exclusive with `create`; requires `file`. Do not combine
            `primary_patient` with `patient_reference`.

        create : typing.Optional[typing.Dict[str, typing.Any]]
            The JSON body of `POST /lang2fhir/create/multi`. Accepts that
            endpoint's fields (`text`, `version`, `provider`,
            `primary_patient`, `patient_reference` (deprecated), `implementation_guide`, `detection_effort`,
            `validation_method`, `resource_review`). This is the
            **multi**-resource body: it has no single-`resource` field, and
            the item's result is a `CreateMultiResponse` (a Bundle of
            resources). Mutually exclusive with `document`; must **not** be
            accompanied by a `file`. Do not combine `primary_patient` with
            `patient_reference`.

        file : typing.Optional[core.File]
            See core.File for more documentation

        request_id : typing.Optional[str]
            Optional idempotency token (at most 256 UTF-8 bytes).
            Re-uploading under the same token overwrites the same item
            instead of adding a new one. The token is scoped to this job;
            the same token in another job is independent and creates a
            separate item.

        id : typing.Optional[str]
            Optional caller-supplied correlation label (at most 512 UTF-8
            bytes), echoed back on status and result listings so you can
            match the server's item_id to your own record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadItemResponse
            Item accepted

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.upload_item(
            job_id="job_id",
        )
        """
        _response = self._raw_client.upload_item(
            job_id,
            document=document,
            create=create,
            file=file,
            request_id=request_id,
            id=id,
            request_options=request_options,
        )
        return _response.data

    def finalize(self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> BatchJob:
        """
        Seals the job's item set and starts processing. Takes no request body.
        Finalize is idempotent: a retried finalize succeeds again.

        If a previous upload did not complete, finalize returns a `409`; re-send
        the missing upload (with the same `request_id`), then finalize.
        Finalizing a job with no items is a `400`.

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            Job finalized and processing started

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.finalize(
            job_id="job_id",
        )
        """
        _response = self._raw_client.finalize(job_id, request_options=request_options)
        return _response.data

    def cancel(self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> BatchJob:
        """
        Drives a job to the terminal `canceled` state on request. Takes no
        request body.

        Cancel does not delete the job: the job record and any results already
        produced are preserved for the normal retention window, the same as a
        `completed` or `failed` job. Items stop being processed and keep the state
        they held at cancellation, so a canceled job's `counts` may show
        unfinished items that never resolve.

        Cancel is idempotent: canceling an already-`canceled` job returns `200`
        with the job. Canceling a job that has already `completed` or `failed` is
        a `409`.

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            The job, now canceled

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.cancel(
            job_id="job_id",
        )
        """
        _response = self._raw_client.cancel(job_id, request_options=request_options)
        return _response.data

    def get(
        self,
        job_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobDetailResponse:
        """
        Returns a job's record, its per-status item counts, and one page of
        per-item statuses.

        Items are listed in a stable order that is not upload order and is the
        same across pages. Match each entry to your own records by its `id`
        (your correlation label) or `item_id` (from the upload response),
        never by position.

        Parameters
        ----------
        job_id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size for the item-status page. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobDetailResponse
            The job record, counts, and a page of item statuses

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.get(
            job_id="job_id",
            cursor="cursor",
            limit=1,
        )
        """
        _response = self._raw_client.get(job_id, cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    def get_results(
        self,
        job_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResultsPageResponse:
        """
        A lighter status page. Returns the same per-item status entries as
        `GET /lang2fhir/batch/{job_id}`, but without the job record or counts,
        and the entries carry `result_size` rather than any result content. Use
        each entry's `item_id` to fetch that item's result from
        `GET /lang2fhir/batch/{job_id}/results/{item_id}`.

        Entries are listed in a stable order that is not upload order and is
        the same across pages. Match each entry to your own records by its `id`
        (your correlation label) or `item_id` (from the upload response),
        never by position.

        Parameters
        ----------
        job_id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResultsPageResponse
            A page of per-item result statuses

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.get_results(
            job_id="job_id",
            cursor="cursor",
            limit=1,
        )
        """
        _response = self._raw_client.get_results(job_id, cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    def get_result(
        self, job_id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Streams one item's stored result bytes verbatim as `application/json`.
        The body is the response the item's synchronous multi endpoint would have
        returned — a `DocumentMultiResponse` for a document item or a
        `CreateMultiResponse` for a create item.

        Only a succeeded item has a result: an item that has not succeeded
        (pending, processing, or failed) is a `409`, and a result that has
        expired is a `404`.

        Parameters
        ----------
        job_id : str

        item_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            The item's raw result JSON

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.lang2fhir_batch.get_result(
            job_id="job_id",
            item_id="item_id",
        )
        """
        _response = self._raw_client.get_result(job_id, item_id, request_options=request_options)
        return _response.data


class AsyncLang2FhirBatchClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawLang2FhirBatchClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawLang2FhirBatchClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawLang2FhirBatchClient
        """
        return self._raw_client

    async def list(
        self,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobListResponse:
        """
        Returns a page of the instance's batch jobs, newest first, without
        per-job counts. Jobs are shared across the instance's credentials, so
        this lists every batch job on the instance, not just the calling
        credential's.

        Parameters
        ----------
        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobListResponse
            A page of batch jobs

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.list(
                cursor="cursor",
                limit=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    async def create(
        self, *, request_id: typing.Optional[str] = OMIT, request_options: typing.Optional[RequestOptions] = None
    ) -> BatchJob:
        """
        Opens an empty job; upload items, then finalize it to start processing.

        `request_id` makes creation idempotent: a retry returns the original
        job. A token is released when its job is canceled or fails before
        finalization; otherwise it continues to resolve to that job.

        Parameters
        ----------
        request_id : typing.Optional[str]
            Optional client idempotency token (at most 256 UTF-8 bytes). A
            retried create with the same token returns the original job instead
            of opening a second one.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            Batch job created (or an idempotent replay of an existing job)

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.create(
                request_id="submit-2025-09-02-batch-001",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(request_id=request_id, request_options=request_options)
        return _response.data

    async def upload_item(
        self,
        job_id: str,
        *,
        document: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        create: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        file: typing.Optional[core.File] = OMIT,
        request_id: typing.Optional[str] = OMIT,
        id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UploadItemResponse:
        """
        Stores one multipart item. Set **either** `document` with a raw `file`,
        or JSON-only `create`.

        Set exactly one JSON object. `document` requires `file`; `create`
        forbids it. Violations return `400`.

        Upload validates only the envelope. Endpoint request validation happens
        during processing: decoding failures are `invalid_input`; other pipeline
        failures are `processing_failed`.

        Use `request_id` for every upload so retries replace the same item.
        `deduplicated` is true only for an unchanged payload; a changed payload
        overwrites the item and returns false.

        Uploads return `409` after finalization or at the item limit, and `413`
        when the item is too large.

        Parameters
        ----------
        job_id : str

        document : typing.Optional[typing.Dict[str, typing.Any]]
            The JSON body of `POST /lang2fhir/document/multi`, **without**
            its base64 `content` field — the uploaded `file` supplies the
            content. Accepts that endpoint's fields (`version`, `provider`,
            `primary_patient`, `patient_reference` (deprecated), `implementation_guide`, `detection_effort`,
            `validation_method`, `config`). This is the **multi**-resource
            body: it has no single-`resource` field, and the item's result
            is a `DocumentMultiResponse` (a Bundle of resources). Mutually
            exclusive with `create`; requires `file`. Do not combine
            `primary_patient` with `patient_reference`.

        create : typing.Optional[typing.Dict[str, typing.Any]]
            The JSON body of `POST /lang2fhir/create/multi`. Accepts that
            endpoint's fields (`text`, `version`, `provider`,
            `primary_patient`, `patient_reference` (deprecated), `implementation_guide`, `detection_effort`,
            `validation_method`, `resource_review`). This is the
            **multi**-resource body: it has no single-`resource` field, and
            the item's result is a `CreateMultiResponse` (a Bundle of
            resources). Mutually exclusive with `document`; must **not** be
            accompanied by a `file`. Do not combine `primary_patient` with
            `patient_reference`.

        file : typing.Optional[core.File]
            See core.File for more documentation

        request_id : typing.Optional[str]
            Optional idempotency token (at most 256 UTF-8 bytes).
            Re-uploading under the same token overwrites the same item
            instead of adding a new one. The token is scoped to this job;
            the same token in another job is independent and creates a
            separate item.

        id : typing.Optional[str]
            Optional caller-supplied correlation label (at most 512 UTF-8
            bytes), echoed back on status and result listings so you can
            match the server's item_id to your own record.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UploadItemResponse
            Item accepted

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.upload_item(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_item(
            job_id,
            document=document,
            create=create,
            file=file,
            request_id=request_id,
            id=id,
            request_options=request_options,
        )
        return _response.data

    async def finalize(self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> BatchJob:
        """
        Seals the job's item set and starts processing. Takes no request body.
        Finalize is idempotent: a retried finalize succeeds again.

        If a previous upload did not complete, finalize returns a `409`; re-send
        the missing upload (with the same `request_id`), then finalize.
        Finalizing a job with no items is a `400`.

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            Job finalized and processing started

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.finalize(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.finalize(job_id, request_options=request_options)
        return _response.data

    async def cancel(self, job_id: str, *, request_options: typing.Optional[RequestOptions] = None) -> BatchJob:
        """
        Drives a job to the terminal `canceled` state on request. Takes no
        request body.

        Cancel does not delete the job: the job record and any results already
        produced are preserved for the normal retention window, the same as a
        `completed` or `failed` job. Items stop being processed and keep the state
        they held at cancellation, so a canceled job's `counts` may show
        unfinished items that never resolve.

        Cancel is idempotent: canceling an already-`canceled` job returns `200`
        with the job. Canceling a job that has already `completed` or `failed` is
        a `409`.

        Parameters
        ----------
        job_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BatchJob
            The job, now canceled

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.cancel(
                job_id="job_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.cancel(job_id, request_options=request_options)
        return _response.data

    async def get(
        self,
        job_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> JobDetailResponse:
        """
        Returns a job's record, its per-status item counts, and one page of
        per-item statuses.

        Items are listed in a stable order that is not upload order and is the
        same across pages. Match each entry to your own records by its `id`
        (your correlation label) or `item_id` (from the upload response),
        never by position.

        Parameters
        ----------
        job_id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size for the item-status page. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        JobDetailResponse
            The job record, counts, and a page of item statuses

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.get(
                job_id="job_id",
                cursor="cursor",
                limit=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(job_id, cursor=cursor, limit=limit, request_options=request_options)
        return _response.data

    async def get_results(
        self,
        job_id: str,
        *,
        cursor: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ResultsPageResponse:
        """
        A lighter status page. Returns the same per-item status entries as
        `GET /lang2fhir/batch/{job_id}`, but without the job record or counts,
        and the entries carry `result_size` rather than any result content. Use
        each entry's `item_id` to fetch that item's result from
        `GET /lang2fhir/batch/{job_id}/results/{item_id}`.

        Entries are listed in a stable order that is not upload order and is
        the same across pages. Match each entry to your own records by its `id`
        (your correlation label) or `item_id` (from the upload response),
        never by position.

        Parameters
        ----------
        job_id : str

        cursor : typing.Optional[str]
            Opaque pagination cursor from a previous page's next_cursor.

        limit : typing.Optional[int]
            Page size. Defaults to 20; values above 100 are clamped to 100.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ResultsPageResponse
            A page of per-item result statuses

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.get_results(
                job_id="job_id",
                cursor="cursor",
                limit=1,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_results(
            job_id, cursor=cursor, limit=limit, request_options=request_options
        )
        return _response.data

    async def get_result(
        self, job_id: str, item_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Streams one item's stored result bytes verbatim as `application/json`.
        The body is the response the item's synchronous multi endpoint would have
        returned — a `DocumentMultiResponse` for a document item or a
        `CreateMultiResponse` for a create item.

        Only a succeeded item has a result: an item that has not succeeded
        (pending, processing, or failed) is a `409`, and a result that has
        expired is a `404`.

        Parameters
        ----------
        job_id : str

        item_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            The item's raw result JSON

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.lang2fhir_batch.get_result(
                job_id="job_id",
                item_id="item_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_result(job_id, item_id, request_options=request_options)
        return _response.data
