# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawSummaryClient, RawSummaryClient
from .types.create_summary_request_mode import CreateSummaryRequestMode
from .types.create_summary_response import CreateSummaryResponse

if typing.TYPE_CHECKING:
    from .templates.client import AsyncTemplatesClient, TemplatesClient
# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SummaryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSummaryClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._templates: typing.Optional[TemplatesClient] = None

    @property
    def with_raw_response(self) -> RawSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSummaryClient
        """
        return self._raw_client

    def create(
        self,
        *,
        fhir_resources: typing.Dict[str, typing.Any],
        mode: typing.Optional[CreateSummaryRequestMode] = OMIT,
        template_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSummaryResponse:
        """
        Creates a summary from FHIR resources using one of three modes:
        - **narrative**: Uses a template to substitute FHIR data into placeholders (requires template_id)
        - **flatten**: Flattens FHIR resources into a searchable format for RAG/search (no template needed)
        - **ips**: Generates an International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG. Requires a Bundle with exactly one Patient resource (returns 400 error if no Patient or multiple Patients are present). Automatically filters resources to those referencing the patient and generates sections for allergies, medications, problems, immunizations, procedures, and vital signs.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle).
            For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
            identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
            if multiple Patients are present, or if the Patient has no identifiers. Resources are
            automatically filtered to only include those referencing the patient.

        mode : typing.Optional[CreateSummaryRequestMode]
            Summary generation mode:
            - narrative: Substitute FHIR data into a template (requires template_id)
            - flatten: Flatten FHIR resources for RAG/search (no template needed)
            - ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG

        template_id : typing.Optional[str]
            ID of the template to use (required for narrative mode)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSummaryResponse
            Summary generated successfully

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.summary.create(
            mode="narrative",
            template_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            fhir_resources={
                "resourceType": "Bundle",
                "type": "collection",
                "entry": [
                    {
                        "resource": {
                            "resourceType": "Patient",
                            "name": [{"given": ["John"], "family": "Doe"}],
                            "gender": "male",
                            "birthDate": "1979-03-15",
                        }
                    },
                    {
                        "resource": {
                            "resourceType": "Condition",
                            "code": {"text": "Type 2 Diabetes Mellitus"},
                            "onsetDateTime": "2024-01-15",
                        }
                    },
                ],
            },
        )
        """
        _response = self._raw_client.create(
            fhir_resources=fhir_resources, mode=mode, template_id=template_id, request_options=request_options
        )
        return _response.data

    @property
    def templates(self):
        if self._templates is None:
            from .templates.client import TemplatesClient  # noqa: E402

            self._templates = TemplatesClient(client_wrapper=self._client_wrapper)
        return self._templates


class AsyncSummaryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSummaryClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._templates: typing.Optional[AsyncTemplatesClient] = None

    @property
    def with_raw_response(self) -> AsyncRawSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSummaryClient
        """
        return self._raw_client

    async def create(
        self,
        *,
        fhir_resources: typing.Dict[str, typing.Any],
        mode: typing.Optional[CreateSummaryRequestMode] = OMIT,
        template_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateSummaryResponse:
        """
        Creates a summary from FHIR resources using one of three modes:
        - **narrative**: Uses a template to substitute FHIR data into placeholders (requires template_id)
        - **flatten**: Flattens FHIR resources into a searchable format for RAG/search (no template needed)
        - **ips**: Generates an International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG. Requires a Bundle with exactly one Patient resource (returns 400 error if no Patient or multiple Patients are present). Automatically filters resources to those referencing the patient and generates sections for allergies, medications, problems, immunizations, procedures, and vital signs.

        Parameters
        ----------
        fhir_resources : typing.Dict[str, typing.Any]
            FHIR resources (single resource or Bundle).
            For IPS mode, must be a Bundle containing exactly one Patient resource with at least one
            identifier (id, fullUrl, or identifier field). Returns an error if no Patient is found,
            if multiple Patients are present, or if the Patient has no identifiers. Resources are
            automatically filtered to only include those referencing the patient.

        mode : typing.Optional[CreateSummaryRequestMode]
            Summary generation mode:
            - narrative: Substitute FHIR data into a template (requires template_id)
            - flatten: Flatten FHIR resources for RAG/search (no template needed)
            - ips: Generate International Patient Summary (IPS) narrative per ISO 27269/HL7 FHIR IPS IG

        template_id : typing.Optional[str]
            ID of the template to use (required for narrative mode)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateSummaryResponse
            Summary generated successfully

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.summary.create(
                mode="narrative",
                template_id="a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                fhir_resources={
                    "resourceType": "Bundle",
                    "type": "collection",
                    "entry": [
                        {
                            "resource": {
                                "resourceType": "Patient",
                                "name": [{"given": ["John"], "family": "Doe"}],
                                "gender": "male",
                                "birthDate": "1979-03-15",
                            }
                        },
                        {
                            "resource": {
                                "resourceType": "Condition",
                                "code": {"text": "Type 2 Diabetes Mellitus"},
                                "onsetDateTime": "2024-01-15",
                            }
                        },
                    ],
                },
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(
            fhir_resources=fhir_resources, mode=mode, template_id=template_id, request_options=request_options
        )
        return _response.data

    @property
    def templates(self):
        if self._templates is None:
            from .templates.client import AsyncTemplatesClient  # noqa: E402

            self._templates = AsyncTemplatesClient(client_wrapper=self._client_wrapper)
        return self._templates
