# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawSummaryClient, RawSummaryClient

if typing.TYPE_CHECKING:
    from .summary_generation.client import AsyncSummaryGenerationClient, SummaryGenerationClient
    from .summary_templates.client import AsyncSummaryTemplatesClient, SummaryTemplatesClient


class SummaryClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSummaryClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._summary_templates: typing.Optional[SummaryTemplatesClient] = None
        self._summary_generation: typing.Optional[SummaryGenerationClient] = None

    @property
    def with_raw_response(self) -> RawSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSummaryClient
        """
        return self._raw_client

    @property
    def summary_templates(self):
        if self._summary_templates is None:
            from .summary_templates.client import SummaryTemplatesClient  # noqa: E402

            self._summary_templates = SummaryTemplatesClient(client_wrapper=self._client_wrapper)
        return self._summary_templates

    @property
    def summary_generation(self):
        if self._summary_generation is None:
            from .summary_generation.client import SummaryGenerationClient  # noqa: E402

            self._summary_generation = SummaryGenerationClient(client_wrapper=self._client_wrapper)
        return self._summary_generation


class AsyncSummaryClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSummaryClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._summary_templates: typing.Optional[AsyncSummaryTemplatesClient] = None
        self._summary_generation: typing.Optional[AsyncSummaryGenerationClient] = None

    @property
    def with_raw_response(self) -> AsyncRawSummaryClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSummaryClient
        """
        return self._raw_client

    @property
    def summary_templates(self):
        if self._summary_templates is None:
            from .summary_templates.client import AsyncSummaryTemplatesClient  # noqa: E402

            self._summary_templates = AsyncSummaryTemplatesClient(client_wrapper=self._client_wrapper)
        return self._summary_templates

    @property
    def summary_generation(self):
        if self._summary_generation is None:
            from .summary_generation.client import AsyncSummaryGenerationClient  # noqa: E402

            self._summary_generation = AsyncSummaryGenerationClient(client_wrapper=self._client_wrapper)
        return self._summary_generation
