# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..types.mcp_server_tool_response import McpServerToolResponse
from .raw_client import AsyncRawMcpToolsClient, RawMcpToolsClient


class McpToolsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMcpToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMcpToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMcpToolsClient
        """
        return self._raw_client

    def list(
        self, mcp_server_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Lists all MCP server tools for a specific MCP server

        Parameters
        ----------
        mcp_server_id : str
            ID of the MCP server to list tools for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully listed MCP server tools

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.tools.mcp_tools.list(
            mcp_server_id="mcp_server_id",
        )
        """
        _response = self._raw_client.list(mcp_server_id, request_options=request_options)
        return _response.data

    def get(
        self, mcp_server_tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Gets a MCP server tool by ID

        Parameters
        ----------
        mcp_server_tool_id : str
            ID of the MCP server tool to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully retrieved MCP server tool

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.tools.mcp_tools.get(
            mcp_server_tool_id="mcp_server_tool_id",
        )
        """
        _response = self._raw_client.get(mcp_server_tool_id, request_options=request_options)
        return _response.data

    def delete(
        self, mcp_server_tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Deletes a MCP server tool by ID

        Parameters
        ----------
        mcp_server_tool_id : str
            ID of the MCP server tool to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully deleted MCP server tool

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.tools.mcp_tools.delete(
            mcp_server_tool_id="mcp_server_tool_id",
        )
        """
        _response = self._raw_client.delete(mcp_server_tool_id, request_options=request_options)
        return _response.data


class AsyncMcpToolsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMcpToolsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMcpToolsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMcpToolsClient
        """
        return self._raw_client

    async def list(
        self, mcp_server_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Lists all MCP server tools for a specific MCP server

        Parameters
        ----------
        mcp_server_id : str
            ID of the MCP server to list tools for

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully listed MCP server tools

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.tools.mcp_tools.list(
                mcp_server_id="mcp_server_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(mcp_server_id, request_options=request_options)
        return _response.data

    async def get(
        self, mcp_server_tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Gets a MCP server tool by ID

        Parameters
        ----------
        mcp_server_tool_id : str
            ID of the MCP server tool to retrieve

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully retrieved MCP server tool

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.tools.mcp_tools.get(
                mcp_server_tool_id="mcp_server_tool_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(mcp_server_tool_id, request_options=request_options)
        return _response.data

    async def delete(
        self, mcp_server_tool_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> McpServerToolResponse:
        """
        Deletes a MCP server tool by ID

        Parameters
        ----------
        mcp_server_tool_id : str
            ID of the MCP server tool to delete

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        McpServerToolResponse
            Successfully deleted MCP server tool

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.tools.mcp_tools.delete(
                mcp_server_tool_id="mcp_server_tool_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(mcp_server_tool_id, request_options=request_options)
        return _response.data
