# This file was auto-generated by Fern from our API Definition.

import typing

from ...core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ...core.request_options import RequestOptions
from ..types.profile_get_response import ProfileGetResponse
from ..types.profile_summary import ProfileSummary
from ..types.profile_version_create_request import ProfileVersionCreateRequest
from ..types.profile_version_list_response import ProfileVersionListResponse
from .raw_client import AsyncRawVersionsClient, RawVersionsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VersionsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVersionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawVersionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVersionsClient
        """
        return self._raw_client

    def list(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ProfileVersionListResponse:
        """
        Returns retained versions for a custom profile.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileVersionListResponse
            List of profile versions

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.profiles.versions.list(
            id="custom-patient",
        )
        """
        _response = self._raw_client.list(id, request_options=request_options)
        return _response.data

    def create(
        self, id: str, *, request: ProfileVersionCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ProfileSummary:
        """
        Adds an immutable StructureDefinition version to a custom profile. If
        the profile does not exist, it is created from the submitted version.
        The StructureDefinition must include a non-empty `version`; its
        canonical URL and resource type must match the profile when one already
        exists. If it includes an `id`, that id must match the path parameter;
        if it omits `id`, the path parameter is used. Profiles created through
        this endpoint are grouped under `custom`. Posting the profile's current
        StructureDefinition unchanged retains it as a version.
        Version strings may contain letters, numbers, and the punctuation
        characters `.`, `_`, `~`, `+`, and `-`; they cannot be exactly `.` or
        `..`. Each profile can retain up to 250 versions; delete old
        versions before adding more.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        request : ProfileVersionCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileSummary
            Profile version successfully created

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.profiles.versions.create(
            id="custom-patient",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.create(id, request=request, request_options=request_options)
        return _response.data

    def get(
        self, id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProfileGetResponse:
        """
        Returns metadata and the full StructureDefinition for one retained
        version. The returned StructureDefinition's id is the profile id. The
        path version is the authored `StructureDefinition.version` value.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        version : str
            The authored StructureDefinition.version. It may contain letters, numbers, and the punctuation characters `.`, `_`, `~`, `+`, and `-`; it cannot be exactly `.` or `..`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileGetResponse
            The requested profile version

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.profiles.versions.get(
            id="custom-patient",
            version="2.0.0",
        )
        """
        _response = self._raw_client.get(id, version, request_options=request_options)
        return _response.data

    def delete(self, id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes one retained version from a custom profile. The path
        version is the authored `StructureDefinition.version` value.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        version : str
            The authored StructureDefinition.version. It may contain letters, numbers, and the punctuation characters `.`, `_`, `~`, `+`, and `-`; it cannot be exactly `.` or `..`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from phenoml import PhenomlClient

        client = PhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.profiles.versions.delete(
            id="custom-patient",
            version="2.0.0",
        )
        """
        _response = self._raw_client.delete(id, version, request_options=request_options)
        return _response.data


class AsyncVersionsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVersionsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawVersionsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVersionsClient
        """
        return self._raw_client

    async def list(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProfileVersionListResponse:
        """
        Returns retained versions for a custom profile.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileVersionListResponse
            List of profile versions

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.profiles.versions.list(
                id="custom-patient",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list(id, request_options=request_options)
        return _response.data

    async def create(
        self, id: str, *, request: ProfileVersionCreateRequest, request_options: typing.Optional[RequestOptions] = None
    ) -> ProfileSummary:
        """
        Adds an immutable StructureDefinition version to a custom profile. If
        the profile does not exist, it is created from the submitted version.
        The StructureDefinition must include a non-empty `version`; its
        canonical URL and resource type must match the profile when one already
        exists. If it includes an `id`, that id must match the path parameter;
        if it omits `id`, the path parameter is used. Profiles created through
        this endpoint are grouped under `custom`. Posting the profile's current
        StructureDefinition unchanged retains it as a version.
        Version strings may contain letters, numbers, and the punctuation
        characters `.`, `_`, `~`, `+`, and `-`; they cannot be exactly `.` or
        `..`. Each profile can retain up to 250 versions; delete old
        versions before adding more.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        request : ProfileVersionCreateRequest

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileSummary
            Profile version successfully created

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.profiles.versions.create(
                id="custom-patient",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create(id, request=request, request_options=request_options)
        return _response.data

    async def get(
        self, id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ProfileGetResponse:
        """
        Returns metadata and the full StructureDefinition for one retained
        version. The returned StructureDefinition's id is the profile id. The
        path version is the authored `StructureDefinition.version` value.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        version : str
            The authored StructureDefinition.version. It may contain letters, numbers, and the punctuation characters `.`, `_`, `~`, `+`, and `-`; it cannot be exactly `.` or `..`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ProfileGetResponse
            The requested profile version

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.profiles.versions.get(
                id="custom-patient",
                version="2.0.0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get(id, version, request_options=request_options)
        return _response.data

    async def delete(self, id: str, version: str, *, request_options: typing.Optional[RequestOptions] = None) -> None:
        """
        Deletes one retained version from a custom profile. The path
        version is the authored `StructureDefinition.version` value.

        Parameters
        ----------
        id : str
            The lowercase StructureDefinition id of the custom profile.

        version : str
            The authored StructureDefinition.version. It may contain letters, numbers, and the punctuation characters `.`, `_`, `~`, `+`, and `-`; it cannot be exactly `.` or `..`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from phenoml import AsyncPhenomlClient

        client = AsyncPhenomlClient(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.profiles.versions.delete(
                id="custom-patient",
                version="2.0.0",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete(id, version, request_options=request_options)
        return _response.data
