# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PageClassification(UniversalBaseModel):
    """
    The classifier's decision for a single page of the input document.
    """

    page_number: typing.Optional[int] = pydantic.Field(default=None)
    """
    1-indexed page number.
    """

    include: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the page was kept (true) or dropped (false) from FHIR extraction.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Short LLM-generated explanation of the decision.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
