# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ResourceReviewTarget(UniversalBaseModel):
    resource_type: str = pydantic.Field()
    """
    FHIR resourceType to audit (e.g. Condition, Procedure, Observation, Encounter, MedicationRequest), matched against each generated resource's resourceType. Patient is not supported.
    """

    fields: typing.Optional[typing.List[typing.Literal["dates"]]] = pydantic.Field(default=None)
    """
    Field kinds to check for this resource type. Defaults to ["dates"] when omitted.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
