# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawFhirClient, RawFhirClient

if typing.TYPE_CHECKING:
    from .fhir_operations.client import AsyncFhirOperationsClient, FhirOperationsClient


class FhirClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFhirClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._fhir_operations: typing.Optional[FhirOperationsClient] = None

    @property
    def with_raw_response(self) -> RawFhirClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFhirClient
        """
        return self._raw_client

    @property
    def fhir_operations(self):
        if self._fhir_operations is None:
            from .fhir_operations.client import FhirOperationsClient  # noqa: E402

            self._fhir_operations = FhirOperationsClient(client_wrapper=self._client_wrapper)
        return self._fhir_operations


class AsyncFhirClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFhirClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._fhir_operations: typing.Optional[AsyncFhirOperationsClient] = None

    @property
    def with_raw_response(self) -> AsyncRawFhirClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFhirClient
        """
        return self._raw_client

    @property
    def fhir_operations(self):
        if self._fhir_operations is None:
            from .fhir_operations.client import AsyncFhirOperationsClient  # noqa: E402

            self._fhir_operations = AsyncFhirOperationsClient(client_wrapper=self._client_wrapper)
        return self._fhir_operations
