# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class TokenResponse(UniversalBaseModel):
    access_token: str = pydantic.Field()
    """
    JWT access token for subsequent authenticated requests
    """

    token_type: str = pydantic.Field()
    """
    Token type (always "Bearer")
    """

    expires_in: int = pydantic.Field()
    """
    Token lifetime in seconds
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
