# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .condition_occurrence_row import ConditionOccurrenceRow
    from .create_omop_response import CreateOmopResponse
    from .dropped_resource import DroppedResource
    from .drug_exposure_row import DrugExposureRow
    from .mapping_entry import MappingEntry
    from .measurement_row import MeasurementRow
    from .observation_row import ObservationRow
    from .omop_tables import OmopTables
    from .person_row import PersonRow
    from .procedure_occurrence_row import ProcedureOccurrenceRow
    from .summary import Summary
    from .visit_occurrence_row import VisitOccurrenceRow
_dynamic_imports: typing.Dict[str, str] = {
    "ConditionOccurrenceRow": ".condition_occurrence_row",
    "CreateOmopResponse": ".create_omop_response",
    "DroppedResource": ".dropped_resource",
    "DrugExposureRow": ".drug_exposure_row",
    "MappingEntry": ".mapping_entry",
    "MeasurementRow": ".measurement_row",
    "ObservationRow": ".observation_row",
    "OmopTables": ".omop_tables",
    "PersonRow": ".person_row",
    "ProcedureOccurrenceRow": ".procedure_occurrence_row",
    "Summary": ".summary",
    "VisitOccurrenceRow": ".visit_occurrence_row",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "ConditionOccurrenceRow",
    "CreateOmopResponse",
    "DroppedResource",
    "DrugExposureRow",
    "MappingEntry",
    "MeasurementRow",
    "ObservationRow",
    "OmopTables",
    "PersonRow",
    "ProcedureOccurrenceRow",
    "Summary",
    "VisitOccurrenceRow",
]
