# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class DeathRow(UniversalBaseModel):
    person_id: typing.Optional[int] = None
    death_date: typing.Optional[str] = None
    death_datetime: typing.Optional[str] = None
    death_type_concept_id: typing.Optional[int] = None
    cause_concept_id: typing.Optional[int] = None
    cause_source_value: typing.Optional[str] = None
    cause_source_concept_id: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
