# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class LocationRow(UniversalBaseModel):
    location_id: typing.Optional[int] = None
    address1: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="address_1"), pydantic.Field(alias="address_1")
    ] = None
    address2: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="address_2"), pydantic.Field(alias="address_2")
    ] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip: typing.Optional[str] = None
    county: typing.Optional[str] = None
    location_source_value: typing.Optional[str] = None
    country_concept_id: typing.Optional[int] = None
    country_source_value: typing.Optional[str] = None
    latitude: typing.Optional[float] = None
    longitude: typing.Optional[float] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
