# This file was auto-generated by Fern from our API Definition.

import typing

MappingEntryMappingStatus = typing.Union[
    typing.Literal["ALREADY_STANDARD", "MAPPED", "UNCHECKED", "UNMAPPED"], typing.Any
]
