# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PersonRow(UniversalBaseModel):
    person_id: typing.Optional[int] = None
    gender_concept_id: typing.Optional[int] = None
    year_of_birth: typing.Optional[int] = pydantic.Field(default=None)
    """
    Year from Patient.birthDate.
    """

    month_of_birth: typing.Optional[int] = pydantic.Field(default=None)
    """
    Month from Patient.birthDate, when it supplies one.
    """

    day_of_birth: typing.Optional[int] = pydantic.Field(default=None)
    """
    Day from Patient.birthDate, when it supplies one.
    """

    birth_datetime: typing.Optional[str] = pydantic.Field(default=None)
    """
    Not set; Patient.birthDate has no time of day.
    """

    race_concept_id: typing.Optional[int] = None
    ethnicity_concept_id: typing.Optional[int] = None
    location_id: typing.Optional[int] = None
    provider_id: typing.Optional[int] = None
    care_site_id: typing.Optional[int] = None
    person_source_value: typing.Optional[str] = None
    gender_source_value: typing.Optional[str] = None
    race_source_value: typing.Optional[str] = None
    ethnicity_source_value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
