# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProviderRow(UniversalBaseModel):
    provider_id: typing.Optional[int] = None
    provider_name: typing.Optional[str] = None
    npi: typing.Optional[str] = None
    dea: typing.Optional[str] = None
    specialty_concept_id: typing.Optional[int] = None
    care_site_id: typing.Optional[int] = None
    year_of_birth: typing.Optional[int] = None
    gender_concept_id: typing.Optional[int] = None
    provider_source_value: typing.Optional[str] = None
    specialty_source_value: typing.Optional[str] = None
    specialty_source_concept_id: typing.Optional[int] = None
    gender_source_value: typing.Optional[str] = None
    gender_source_concept_id: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
