# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .reference_diagnostic_outcome import ReferenceDiagnosticOutcome


class ReferenceDiagnostic(UniversalBaseModel):
    resource_type: typing.Optional[str] = None
    resource_id: typing.Optional[str] = None
    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    FHIR element path on the source resource.
    """

    reference: typing.Optional[str] = pydantic.Field(default=None)
    """
    The supplied Reference.reference value, when present.
    """

    outcome: typing.Optional[ReferenceDiagnosticOutcome] = None
    reason: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
