# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .reference_diagnostic_outcome import ReferenceDiagnosticOutcome


class ReferenceDiagnostic(UniversalBaseModel):
    """
    Explains why a source value or reference could not be used. When an affected OMOP row is emitted, omop_table and omop_id identify that row within this response, regardless of diagnostic outcome. They identify the affected output row, not a missing or rejected reference target. Multiple source resources can link to the same row. Both fields are omitted when there is no affected output row, including when the source resource is dropped. These IDs are response-local and are not stable across requests.
    """

    resource_type: typing.Optional[str] = None
    resource_id: typing.Optional[str] = None
    omop_table: typing.Optional[str] = pydantic.Field(default=None)
    """
    Table containing the affected row in this response. Present together with omop_id when that row is emitted.
    """

    omop_id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Primary key of the affected row within omop_table in this response. Present together with omop_table when that row is emitted.
    """

    path: typing.Optional[str] = pydantic.Field(default=None)
    """
    FHIR element path on the source resource.
    """

    reference: typing.Optional[str] = pydantic.Field(default=None)
    """
    The supplied Reference.reference value, when present.
    """

    outcome: typing.Optional[ReferenceDiagnosticOutcome] = pydantic.Field(default=None)
    """
    UNRESOLVED: a supported reference cannot resolve to a resource or
    emitted target supplied in this request.
    AMBIGUOUS: a reference or identifier matches multiple possible
    targets. Identifier-only `PractitionerRole.practitioner` references
    are unambiguous when all matches map to one canonical provider.
    Literal references matching multiple source resources remain
    ambiguous even if those Practitioners merge into one provider.
    CONFLICTING: supplied values or relationships cannot be combined
    under the mapping policy, such as differing mapped provider identity
    attributes, multiple distinct NPIs on one Practitioner, conflicting
    Patient demographic extensions, or an Encounter belonging to a
    different patient.
    UNSUPPORTED: a supplied reference form, resource type, or value
    shape is outside the supported mapping policy.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Explanation of the condition and, when applicable, its effect on mapping.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
