# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Summary(UniversalBaseModel):
    """
    The request's data-quality headline: how the coded concepts split across
    resolution outcomes, and the share that was not already in a target
    standard vocabulary.
    """

    codes_already_standard: typing.Optional[int] = pydantic.Field(default=None)
    """
    Codings already a standard OMOP concept.
    """

    codes_normalized: typing.Optional[int] = pydantic.Field(default=None)
    """
    Codings mapped or suggested to a standard concept (MAPPED or UNCHECKED).
    """

    codes_unmapped: typing.Optional[int] = pydantic.Field(default=None)
    """
    Codings with no standard concept found.
    """

    off_vocab_rate: typing.Optional[float] = pydantic.Field(default=None)
    """
    Share of coded concepts not already standard ((normalized + unmapped) / total).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
