# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class VisitOccurrenceRow(UniversalBaseModel):
    visit_occurrence_id: typing.Optional[int] = None
    person_id: typing.Optional[int] = None
    visit_concept_id: typing.Optional[int] = None
    visit_start_date: typing.Optional[str] = None
    visit_start_datetime: typing.Optional[str] = None
    visit_end_date: typing.Optional[str] = None
    visit_end_datetime: typing.Optional[str] = None
    visit_type_concept_id: typing.Optional[int] = None
    visit_source_value: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
