# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from .raw_client import AsyncRawVoiceClient, RawVoiceClient

if typing.TYPE_CHECKING:
    from .voice.client import AsyncVoiceClient as voice_voice_client_AsyncVoiceClient
    from .voice.client import VoiceClient as voice_voice_client_VoiceClient


class VoiceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawVoiceClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._voice: typing.Optional[voice_voice_client_VoiceClient] = None

    @property
    def with_raw_response(self) -> RawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawVoiceClient
        """
        return self._raw_client

    @property
    def voice(self):
        if self._voice is None:
            from .voice.client import VoiceClient as voice_voice_client_VoiceClient  # noqa: E402

            self._voice = voice_voice_client_VoiceClient(client_wrapper=self._client_wrapper)
        return self._voice


class AsyncVoiceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawVoiceClient(client_wrapper=client_wrapper)
        self._client_wrapper = client_wrapper
        self._voice: typing.Optional[voice_voice_client_AsyncVoiceClient] = None

    @property
    def with_raw_response(self) -> AsyncRawVoiceClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawVoiceClient
        """
        return self._raw_client

    @property
    def voice(self):
        if self._voice is None:
            from .voice.client import AsyncVoiceClient as voice_voice_client_AsyncVoiceClient  # noqa: E402

            self._voice = voice_voice_client_AsyncVoiceClient(client_wrapper=self._client_wrapper)
        return self._voice
