# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        CreateMultiRequestDetectionEffort,
        CreateMultiRequestValidationMethod,
        CreateMultiResponse,
        CreateMultiResponseBundle,
        CreateMultiResponseBundleEntryItem,
        CreateMultiResponseBundleEntryItemRequest,
        CreateMultiResponseResourcesItem,
        CreateMultiResponseValidation,
        CreateMultiResponseValidationPassesItem,
        CreateMultiResponseValidationPassesItemIssuesItem,
        CreateMultiResponseValidationPassesItemIssuesItemSeverity,
        CreateMultiResponseValidationPassesItemStats,
        CreateRequestResource,
        DocumentConfig,
        DocumentMultiRequestDetectionEffort,
        DocumentMultiRequestValidationMethod,
        DocumentMultiResponse,
        FhirResource,
        PageClassification,
        PageFilter,
        ProfileUploadRequest,
        SearchResponse,
        SearchResponseResourceType,
        UploadProfileResponse,
    )
    from .errors import (
        BadRequestError,
        ClientClosedRequestError,
        ForbiddenError,
        GatewayTimeoutError,
        InternalServerError,
        NotFoundError,
        UnauthorizedError,
        UnprocessableEntityError,
    )
_dynamic_imports: typing.Dict[str, str] = {
    "BadRequestError": ".errors",
    "ClientClosedRequestError": ".errors",
    "CreateMultiRequestDetectionEffort": ".types",
    "CreateMultiRequestValidationMethod": ".types",
    "CreateMultiResponse": ".types",
    "CreateMultiResponseBundle": ".types",
    "CreateMultiResponseBundleEntryItem": ".types",
    "CreateMultiResponseBundleEntryItemRequest": ".types",
    "CreateMultiResponseResourcesItem": ".types",
    "CreateMultiResponseValidation": ".types",
    "CreateMultiResponseValidationPassesItem": ".types",
    "CreateMultiResponseValidationPassesItemIssuesItem": ".types",
    "CreateMultiResponseValidationPassesItemIssuesItemSeverity": ".types",
    "CreateMultiResponseValidationPassesItemStats": ".types",
    "CreateRequestResource": ".types",
    "DocumentConfig": ".types",
    "DocumentMultiRequestDetectionEffort": ".types",
    "DocumentMultiRequestValidationMethod": ".types",
    "DocumentMultiResponse": ".types",
    "FhirResource": ".types",
    "ForbiddenError": ".errors",
    "GatewayTimeoutError": ".errors",
    "InternalServerError": ".errors",
    "NotFoundError": ".errors",
    "PageClassification": ".types",
    "PageFilter": ".types",
    "ProfileUploadRequest": ".types",
    "SearchResponse": ".types",
    "SearchResponseResourceType": ".types",
    "UnauthorizedError": ".errors",
    "UnprocessableEntityError": ".errors",
    "UploadProfileResponse": ".types",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "BadRequestError",
    "ClientClosedRequestError",
    "CreateMultiRequestDetectionEffort",
    "CreateMultiRequestValidationMethod",
    "CreateMultiResponse",
    "CreateMultiResponseBundle",
    "CreateMultiResponseBundleEntryItem",
    "CreateMultiResponseBundleEntryItemRequest",
    "CreateMultiResponseResourcesItem",
    "CreateMultiResponseValidation",
    "CreateMultiResponseValidationPassesItem",
    "CreateMultiResponseValidationPassesItemIssuesItem",
    "CreateMultiResponseValidationPassesItemIssuesItemSeverity",
    "CreateMultiResponseValidationPassesItemStats",
    "CreateRequestResource",
    "DocumentConfig",
    "DocumentMultiRequestDetectionEffort",
    "DocumentMultiRequestValidationMethod",
    "DocumentMultiResponse",
    "FhirResource",
    "ForbiddenError",
    "GatewayTimeoutError",
    "InternalServerError",
    "NotFoundError",
    "PageClassification",
    "PageFilter",
    "ProfileUploadRequest",
    "SearchResponse",
    "SearchResponseResourceType",
    "UnauthorizedError",
    "UnprocessableEntityError",
    "UploadProfileResponse",
]
