# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_server import McpServer
from .mcp_server_tool import McpServerTool


class McpServerResponse(UniversalBaseModel):
    success: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the operation succeeded
    """

    message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Status message
    """

    data: typing.Optional[McpServer] = pydantic.Field(default=None)
    """
    Single MCP server (returned by GET /tools/mcp-server/{mcp_server_id}).
    """

    mcp_servers: typing.Optional[typing.List[McpServer]] = pydantic.Field(default=None)
    """
    List of MCP servers. Returned by /tools/mcp-server/create (the
    newly created server) and /tools/mcp-server/list (all servers).
    """

    mcp_server_tools: typing.Optional[typing.List[McpServerTool]] = pydantic.Field(default=None)
    """
    Tools loaded from the MCP server. Returned by /tools/mcp-server/create
    alongside the server record, since tool discovery happens at create time.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
