# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CodeCategory(UniversalBaseModel):
    """
    A higher-level grouping (e.g. HPO category) for an extracted code.
    """

    uri: str = pydantic.Field()
    """
    Identifier for the category term (e.g. an HPO URI).
    """

    label: str = pydantic.Field()
    """
    Human-readable label for the category term.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
